#! /bin/bash

. /etc/rc.conf
. /etc/rc.d/functions

case "$1" in
  start)
	stat_busy "Starting LOLastfm"
	LOLastfm &> /dev/null &
	pgrep LOLastfm > /var/run/LOLastfm.pid
	if [ $? -gt 0 ]; then
      stat_fail
    else
      add_daemon LOLastfm
	  stat_done
    fi
    ;;
  stop)
	stat_busy "Stopping LOLastfm"
	[ -f /var/run/LOLastfm.pid ] && kill $(cat /var/run/LOLastfm.pid) &> /dev/null
	if [ $? -gt 0 ]; then
      stat_fail
    else
      rm -f /var/run/LOLastfm.pid
	  rm_daemon LOLastfm
	  stat_done
    fi
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  *)
    echo "usage: $0 {start|stop|restart}"
esac
exit 0
