#! /bin/sh

case "$1" in
    start)
        if [ -e /tmp/LOLastfm.pid ]; then
            echo "LOLastfm is already started.";
        fi

        echo "Starting LOLastfm..."
        LOLastfm &> /dev/null &
        echo $$ > /tmp/LOLastfm.pid
    ;;

    stop)
        echo "Stopping LOLastfm..."
        kill `cat /tmp/LOLastfm.pid` &> /dev/null
        rm /tmp/LOLastfm.pid
    ;;

    restart)
        $0 stop
        $0 start
    ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
    ;;
esac

exit 0
